"""Increase password hash length

Revision ID: 228f33cec21b
Revises: 20555c1fa355
Create Date: 2025-10-14 15:54:50.813605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '228f33cec21b'
down_revision = '20555c1fa355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
